files:
  - source: /translations.xlsx
    translation: /translations_%locale_with_underscore%.xlsx
    first_line_contains_header: 'true'
    scheme: 'source_phrase, en-UK, jp, kr, pt-PT, de,  cs, nl, zh-CN, zh-TW, fi, fr-FR, es-ES, it-IT, ru, ar'
